import type { Metadata } from "next";
import { Tajawal } from "next/font/google";
import "./globals.css";
import Nav from "@/components/global/Nav";
import Footer from "@/components/global/footer/Footer";

const cairo = Tajawal({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700", "800", "900"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.className} mt-[87px] relative`}>
        <Nav />
        <div className="mt-[86.39]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
